### ISSUE TITLE
Update community repository

### ISSUE THREAD

**Issue by cyberswat** [drud/community#29]
## Feature Description:
We've recently implemented significant changes to our company structure and workflows. This repository should be updated to reflect the latest changes in pod structure, standups, and technical workflow.

This is an epic and should be flushed out accordingly.

## User stories:
- [ ] As a community documentation contributor I would like to have updated issue templates for the drud/community repository. #30 
- [ ] As a communty member, I want to understand how DDEV manages work from idea to delivery.
- [ ] As a communty member, I want to understand the concept pods.
- [ ] As a pod member, I want to understand my roles and responsibilities.
- [ ] As a pod lead, I want to understand my roles and responsibilites.
- [ ] As a pod project manager, I want to understand my roles and responsibilites.
- [ ] As a product manager, I want to understand my roles and responsibilites as they relate to moving ideas into deliveries.
- [ ] As a project manager, I want to understand my roles and responsibilites necessary to support pods.
- [ ] As a praticipant in standups I would like to know how to participate.

## Acceptance criteria:
- [ ] Updated github templates are in place for drud/community
- [ ] Current documentation is updated to satisfy the user stories on this epic.
- [ ] Readthedocs is generating documentation instead of github - #35 

## Related links or issues:

- [ddev-webserver image build and start](https://www.notion.so/drud/drud-ddev-webserver-structure-build-behavior-ce297978f6d54798b07fb4fbef66e372)
- buildpacks demo and notes [in this folder](https://drive.google.com/drive/folders/1clxTdB8Hokk30YjRMQtaTrh7aGoIgPVM):
- State of things today: [Live](https://github.com/drud/site-operator/blob/master/pkg/controller/phpdistro/docker.go) | [Local](https://github.com/drud/ddev/blob/master/containers/ddev-webserver/Dockerfile)

## Definition of Ready Checklist:

- [ ] User-facing feature: provides story or A/C in [Gherkin format](https://cucumber.io/docs/gherkin), or
- [ ] Architectural feature: provides technical A/C
- [ ] Dependencies identified
- [ ] Sized by team

R<sup>Product Owner</sup> A<sup>Scrum Master</sup> C<sup>Eng. Lead</sup> I<sup>Team</sup>

## Definition of Done Checklist:

- [ ] Acceptance Criteria tested and passing
- [ ] Deployed on test environment
- [ ] QA performed & issues resolved
- [ ] Unit test and E2E coverage updated (if applicable)
- [ ] Builds without errors
- [ ] Internal documentation updated (if required)

R<sup>Eng. Lead, Team</sup> A<sup>Scrum Master</sup> CI<sup>Product Owner</sup>

**Comment by cyberswat** [comment]
Linking to https://github.com/drud/ddev-live/issues/208 as relevant.
